<#
.SYNOPSIS
    Political Spectrum App - One-Click Setup Script
.DESCRIPTION
    Automated setup script for the Political Spectrum App with progress tracking,
    logging, error handling, and troubleshooting capabilities.
.VERSION
    2.3.0
.AUTHOR
    Shootre21
.REPOSITORY
    https://github.com/Shootre21/political-spectrum-app-v2
#>

#Requires -Version 5.1

param(
    [switch]$SkipDeps,
    [switch]$SkipDB,
    [switch]$SkipEnv,
    [switch]$Force,
    [switch]$Verbose,
    [string]$LogFile = ".\setup.log"
)

# ============================================
# CONFIGURATION
# ============================================
$Config = @{
    AppName = "Political Spectrum App"
    Version = "2.5.0"
    NodeMinVersion = "18.0.0"
    BunMinVersion = "1.0.0"
    RequiredPorts = @(3000, 5555)
    # Default demo credentials - USER MUST CHANGE THESE!
    DefaultCredentials = @{
        OPENAI_API_KEY = "sk-demo-REPLACE-WITH-YOUR-KEY"
        ANTHROPIC_API_KEY = "sk-ant-demo-REPLACE-WITH-YOUR-KEY"
        KIMI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        ZAI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        GROK_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        GEMINI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
    }
    EnvTemplate = @'
# Political Spectrum App - Environment Variables
# Generated by setup.ps1
# 
# ⚠️  WARNING: Default demo credentials are set below.
#    You MUST replace these with your actual API keys!
#    Get your keys from:
#    - OpenAI: https://platform.openai.com/api-keys
#    - Anthropic: https://console.anthropic.com/
#    - Google Gemini: https://makersuite.google.com/app/apikey
#    - xAI Grok: https://console.x.ai/
#    - Kimi: https://platform.moonshot.cn/
#    - Z.ai: Contact Z.ai for API access

# Database
DATABASE_URL="file:./dev.db"

# AI Provider API Keys (⚠️ REPLACE THESE WITH YOUR ACTUAL KEYS!)
OPENAI_API_KEY="sk-demo-REPLACE-WITH-YOUR-KEY"
ANTHROPIC_API_KEY="sk-ant-demo-REPLACE-WITH-YOUR-KEY"
KIMI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
ZAI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
GROK_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
GEMINI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"

# Site URL for SEO
NEXT_PUBLIC_SITE_URL="http://localhost:3000"
'@
}

# ============================================
# LOGGING SYSTEM
# ============================================
function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO', 'WARN', 'ERROR', 'SUCCESS', 'DEBUG')]
        [string]$Level = 'INFO'
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] [$Level] $Message"
    
    # Write to log file
    try {
        Add-Content -Path $LogFile -Value $logEntry -ErrorAction SilentlyContinue
    } catch {}
    
    # Console output with colors
    switch ($Level) {
        'INFO'    { Write-Host $logEntry -ForegroundColor Cyan }
        'WARN'    { Write-Host $logEntry -ForegroundColor Yellow }
        'ERROR'   { Write-Host $logEntry -ForegroundColor Red }
        'SUCCESS' { Write-Host $logEntry -ForegroundColor Green }
        'DEBUG'   { if ($Verbose) { Write-Host $logEntry -ForegroundColor Gray } }
    }
}

function Write-Header {
    param([string]$Title)
    
    $width = 60
    $padding = [Math]::Max(0, ($width - $Title.Length) / 2)
    
    Write-Host ""
    Write-Host ("=" * $width) -ForegroundColor DarkCyan
    Write-Host (" " * [Math]::Floor($padding) + $Title) -ForegroundColor Cyan
    Write-Host ("=" * $width) -ForegroundColor DarkCyan
    Write-Host ""
}

# ============================================
# PROGRESS BAR SYSTEM
# ============================================
$Script:Progress = @{
    Current = 0
    Total = 10
    Activity = "Setting up Political Spectrum App"
}

function Show-Progress {
    param(
        [string]$Status,
        [int]$Increment = 1
    )
    
    $Script:Progress.Current += $Increment
    $percent = [Math]::Min(100, [Math]::Round(($Script:Progress.Current / $Script:Progress.Total) * 100))
    
    # Create progress bar string
    $barWidth = 30
    $filled = [Math]::Round($barWidth * ($percent / 100))
    $empty = $barWidth - $filled
    $bar = "[" + ("=" * $filled) + (" " * $empty) + "]"
    
    Write-Host "`r$bar $percent% - $Status" -NoNewline -ForegroundColor Yellow
    
    if ($Script:Progress.Current -ge $Script:Progress.Total) {
        Write-Host ""
    }
}

function Reset-Progress {
    param([int]$Total = 10)
    $Script:Progress.Current = 0
    $Script:Progress.Total = $Total
}

# ============================================
# ERROR HANDLING SYSTEM
# ============================================
$Script:Errors = @()
$Script:Warnings = @()

function Add-Error {
    param(
        [string]$Code,
        [string]$Message,
        [string]$Solution,
        [bool]$Fatal = $false
    )
    
    $errorObj = @{
        Code = $Code
        Message = $Message
        Solution = $Solution
        Fatal = $Fatal
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    $Script:Errors += $errorObj
    Write-Log $Message -Level ERROR
    
    if ($Fatal) {
        Show-ErrorSummary
        throw "Fatal error occurred: $Message"
    }
}

function Add-Warning {
    param(
        [string]$Code,
        [string]$Message,
        [string]$Solution
    )
    
    $warningObj = @{
        Code = $Code
        Message = $Message
        Solution = $Solution
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    $Script:Warnings += $warningObj
    Write-Log $Message -Level WARN
}

function Show-ErrorSummary {
    Write-Header "Setup Summary"
    
    if ($Script:Errors.Count -eq 0 -and $Script:Warnings.Count -eq 0) {
        Write-Host "  [OK] No errors or warnings encountered!" -ForegroundColor Green
        return
    }
    
    if ($Script:Errors.Count -gt 0) {
        Write-Host "`n  ERRORS ($($Script:Errors.Count)):" -ForegroundColor Red
        foreach ($err in $Script:Errors) {
            Write-Host "    [$($err.Code)] $($err.Message)" -ForegroundColor Red
            Write-Host "           Solution: $($err.Solution)" -ForegroundColor Yellow
        }
    }
    
    if ($Script:Warnings.Count -gt 0) {
        Write-Host "`n  WARNINGS ($($Script:Warnings.Count)):" -ForegroundColor Yellow
        foreach ($warn in $Script:Warnings) {
            Write-Host "    [$($warn.Code)] $($warn.Message)" -ForegroundColor Yellow
            Write-Host "           Solution: $($warn.Solution)" -ForegroundColor Cyan
        }
    }
    
    Write-Host ""
}

# ============================================
# COMMON ERROR DEFINITIONS
# ============================================
$ErrorCodes = @{
    E001 = @{
        Message = "Node.js is not installed"
        Solution = "Install Node.js 18+ from https://nodejs.org or run: winget install OpenJS.NodeJS.LTS"
    }
    E002 = @{
        Message = "Node.js version is too old"
        Solution = "Update Node.js to version 18 or higher"
    }
    E003 = @{
        Message = "Bun is not installed"
        Solution = "Install Bun from https://bun.sh or run: powershell -c 'irm bun.sh/install.ps1 | iex'"
    }
    E004 = @{
        Message = "Port 3000 is already in use"
        Solution = "Stop the process using port 3000: Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess | Stop-Process -Force"
    }
    E005 = @{
        Message = "Package installation failed"
        Solution = "Try: Remove-Item node_modules -Recurse -Force; bun install"
    }
    E006 = @{
        Message = "Database migration failed"
        Solution = "Try: npx prisma migrate reset --force"
    }
    E007 = @{
        Message = "Prisma client generation failed"
        Solution = "Try: npx prisma generate"
    }
    E008 = @{
        Message = "Environment file creation failed"
        Solution = "Create .env file manually with DATABASE_URL='file:./dev.db'"
    }
    E009 = @{
        Message = "Build failed"
        Solution = "Check error logs and ensure all dependencies are installed"
    }
    E010 = @{
        Message = "Git is not installed"
        Solution = "Install Git from https://git-scm.com or run: winget install Git.Git"
    }
    E011 = @{
        Message = "Insufficient disk space"
        Solution = "Free up at least 500MB of disk space"
    }
    E012 = @{
        Message = "Permission denied"
        Solution = "Run PowerShell as Administrator or check folder permissions"
    }
    E013 = @{
        Message = "Network connection failed"
        Solution = "Check your internet connection and proxy settings"
    }
    E014 = @{
        Message = "Prisma CLI not found"
        Solution = "Run: bun add prisma @prisma/client"
    }
    E015 = @{
        Message = "SQLite database locked"
        Solution = "Close any applications using the database and try again"
    }
}

function Get-ErrorSolution {
    param([string]$Code)
    
    if ($ErrorCodes.ContainsKey($Code)) {
        return $ErrorCodes[$Code]
    }
    return @{ Message = "Unknown error"; Solution = "Check the documentation or GitHub issues" }
}

# ============================================
# SYSTEM CHECKS
# ============================================
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-CommandExists {
    param([string]$Command)
    return $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

function Test-PortAvailable {
    param([int]$Port)
    $connection = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue
    return $null -eq $connection
}

function Get-NodeVersion {
    if (Test-CommandExists "node") {
        $version = node --version
        return $version -replace 'v', ''
    }
    return $null
}

function Compare-Versions {
    param([string]$V1, [string]$V2)
    
    $v1Parts = $V1.Split('.')
    $v2Parts = $V2.Split('.')
    
    for ($i = 0; $i -lt [Math]::Max($v1Parts.Length, $v2Parts.Length); $i++) {
        $v1Num = if ($i -lt $v1Parts.Length) { [int]$v1Parts[$i] } else { 0 }
        $v2Num = if ($i -lt $v2Parts.Length) { [int]$v2Parts[$i] } else { 0 }
        
        if ($v1Num -gt $v2Num) { return 1 }
        if ($v1Num -lt $v2Num) { return -1 }
    }
    return 0
}

function Test-DiskSpace {
    param([string]$Path, [long]$RequiredMB = 500)
    
    try {
        $drive = (Get-Item $Path -ErrorAction SilentlyContinue).PSDrive
        if (-not $drive) {
            $drive = Get-PSDrive -Name $Path.Substring(0,1)
        }
        $freeSpaceMB = [Math]::Round($drive.Free / 1MB, 2)
        return $freeSpaceMB -ge $RequiredMB
    } catch {
        return $true  # Assume OK if can't check
    }
}

# ============================================
# SETUP STEPS
# ============================================
function Invoke-PrerequisitesCheck {
    Show-Progress "Checking prerequisites..."
    
    Write-Log "Starting prerequisites check" -Level INFO
    
    # Check if running as admin (warn but don't fail)
    if (-not (Test-Administrator)) {
        Add-Warning "W001" "Not running as Administrator" "Some features may require elevated permissions"
    }
    
    # Check disk space
    if (-not (Test-DiskSpace $PWD)) {
        $error = Get-ErrorSolution "E011"
        Add-Error "E011" $error.Message $error.Solution -Fatal $false
    }
    
    # Check Node.js
    $nodeVersion = Get-NodeVersion
    if (-not $nodeVersion) {
        $error = Get-ErrorSolution "E001"
        Add-Error "E001" $error.Message $error.Solution -Fatal $true
    }
    
    if ((Compare-Versions $nodeVersion $Config.NodeMinVersion) -lt 0) {
        $error = Get-ErrorSolution "E002"
        Add-Error "E002" "$($error.Message) (Current: $nodeVersion, Required: $($Config.NodeMinVersion))" $error.Solution -Fatal $true
    }
    
    Write-Log "Node.js version: $nodeVersion" -Level SUCCESS
    
    # Check Bun (preferred) or npm
    if (-not (Test-CommandExists "bun")) {
        Add-Warning "W002" "Bun is not installed (recommended)" "Install from https://bun.sh for faster performance"
        
        if (-not (Test-CommandExists "npm")) {
            $error = Get-ErrorSolution "E003"
            Add-Error "E003" "Neither Bun nor npm is available" $error.Solution -Fatal $true
        }
        
        $Script:PackageManager = "npm"
    } else {
        $Script:PackageManager = "bun"
        Write-Log "Using Bun as package manager" -Level SUCCESS
    }
    
    # Check Git
    if (-not (Test-CommandExists "git")) {
        Add-Warning "W003" "Git is not installed" "Required for version control: winget install Git.Git"
    }
    
    # Check ports
    foreach ($port in $Config.RequiredPorts) {
        if (-not (Test-PortAvailable $port)) {
            $error = Get-ErrorSolution "E004"
            Add-Warning "W004" "Port $port is already in use" $error.Solution
        }
    }
    
    Show-Progress "Prerequisites checked" 1
    return $true
}

function Invoke-DependencyInstall {
    Show-Progress "Installing dependencies..."
    
    Write-Log "Starting dependency installation" -Level INFO
    
    # Clean install if Force flag or node_modules missing
    if ($Force -or -not (Test-Path "node_modules")) {
        if (Test-Path "node_modules") {
            Write-Log "Removing existing node_modules..." -Level INFO
            Remove-Item "node_modules" -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    
    # Install dependencies
    $installCmd = if ($Script:PackageManager -eq "bun") {
        "bun install"
    } else {
        "npm install"
    }
    
    Write-Log "Running: $installCmd" -Level DEBUG
    
    try {
        $result = Invoke-Expression "$installCmd 2>&1"
        if ($LASTEXITCODE -ne 0) {
            $error = Get-ErrorSolution "E005"
            Add-Error "E005" $error.Message $error.Solution -Fatal $false
            Write-Log "Install output: $result" -Level DEBUG
            
            # Retry with npm if bun failed
            if ($Script:PackageManager -eq "bun") {
                Write-Log "Retrying with npm..." -Level WARN
                npm install
                if ($LASTEXITCODE -ne 0) {
                    Add-Error "E005" "Package installation failed after retry" $error.Solution -Fatal $true
                }
            }
        }
        
        Write-Log "Dependencies installed successfully" -Level SUCCESS
    } catch {
        $error = Get-ErrorSolution "E005"
        Add-Error "E005" "$($error.Message): $_" $error.Solution -Fatal $true
    }
    
    Show-Progress "Dependencies installed" 1
}

function Invoke-DatabaseSetup {
    Show-Progress "Setting up database..."
    
    Write-Log "Starting database setup" -Level INFO
    
    # Ensure prisma is available
    if (-not (Test-Path "node_modules\.bin\prisma") -and -not (Test-CommandExists "prisma")) {
        Add-Warning "W005" "Prisma CLI not found" "Installing Prisma..."
        
        if ($Script:PackageManager -eq "bun") {
            bun add prisma @prisma/client
        } else {
            npm install prisma @prisma/client
        }
    }
    
    # Generate Prisma client
    Write-Log "Generating Prisma client..." -Level INFO
    try {
        npx prisma generate 2>&1 | Out-Null
        Write-Log "Prisma client generated" -Level SUCCESS
    } catch {
        $error = Get-ErrorSolution "E007"
        Add-Error "E007" $error.Message $error.Solution -Fatal $false
    }
    
    # Run migrations
    Write-Log "Running database migrations..." -Level INFO
    
    if (-not (Test-Path "prisma\dev.db")) {
        try {
            npx prisma migrate dev --name init 2>&1 | Out-Null
            Write-Log "Database migrations completed" -Level SUCCESS
        } catch {
            # Try push if migrate fails
            Write-Log "Migration failed, trying db push..." -Level WARN
            try {
                npx prisma db push 2>&1 | Out-Null
                Write-Log "Database schema pushed successfully" -Level SUCCESS
            } catch {
                $error = Get-ErrorSolution "E006"
                Add-Error "E006" $error.Message $error.Solution -Fatal $false
            }
        }
    } else {
        Write-Log "Database already exists, skipping migration" -Level INFO
    }
    
    Show-Progress "Database configured" 1
}

function Invoke-EnvironmentSetup {
    Show-Progress "Configuring environment..."
    
    Write-Log "Setting up environment" -Level INFO
    
    $envFile = ".env"
    $envLocalFile = ".env.local"
    
    # Create .env if missing
    if (-not (Test-Path $envFile)) {
        try {
            $Config.EnvTemplate | Out-File -FilePath $envFile -Encoding utf8
            Write-Log "Created .env file with default credentials" -Level SUCCESS
            
            # Show warning about default credentials
            Write-Host ""
            Write-Host "  ⚠️  WARNING: Default demo credentials have been set!" -ForegroundColor Yellow
            Write-Host "  ─────────────────────────────────────────────────" -ForegroundColor DarkYellow
            Write-Host "  The following API keys are placeholders and will NOT work:" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "    • OPENAI_API_KEY = 'sk-demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host "    • ANTHROPIC_API_KEY = 'sk-ant-demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host "    • GEMINI_API_KEY = 'demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host "    • GROK_API_KEY = 'demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host ""
            Write-Host "  You MUST replace these with your actual API keys!" -ForegroundColor Yellow
            Write-Host ""
        } catch {
            $error = Get-ErrorSolution "E008"
            Add-Error "E008" $error.Message $error.Solution -Fatal $false
        }
    } else {
        Write-Log ".env file already exists" -Level INFO
        
        # Check if default credentials are still present
        $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
        if ($envContent -match "sk-demo-REPLACE" -or $envContent -match "demo-REPLACE") {
            Write-Host ""
            Write-Host "  ⚠️  WARNING: Default demo credentials detected!" -ForegroundColor Yellow
            Write-Host "  ─────────────────────────────────────────────────" -ForegroundColor DarkYellow
            Write-Host "  Your .env file contains placeholder API keys." -ForegroundColor Yellow
            Write-Host "  AI analysis features will NOT work until you replace them." -ForegroundColor Yellow
            Write-Host ""
        }
    }
    
    # Create .env.local if missing
    if (-not (Test-Path $envLocalFile)) {
        try {
            "# Local environment overrides`n# Add your actual API keys here to override the demo values" | Out-File -FilePath $envLocalFile -Encoding utf8
            Write-Log "Created .env.local file" -Level SUCCESS
        } catch {
            Write-Log "Could not create .env.local" -Level WARN
        }
    }
    
    # Verify DATABASE_URL
    $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
    if ($envContent -notmatch "DATABASE_URL") {
        Add-Content -Path $envFile -Value 'DATABASE_URL="file:./dev.db"'
        Write-Log "Added DATABASE_URL to .env" -Level INFO
    }
    
    Show-Progress "Environment configured" 1
}

function Invoke-CredentialsPrompt {
    Show-Progress "Checking API credentials..."
    
    Write-Log "Checking API credentials status" -Level INFO
    
    $envFile = ".env"
    if (-not (Test-Path $envFile)) {
        return
    }
    
    $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
    
    # Check for demo credentials
    $hasDemoCreds = $envContent -match "sk-demo-REPLACE" -or $envContent -match "demo-REPLACE"
    
    if ($hasDemoCreds) {
        Write-Host ""
        Write-Host "  ╔════════════════════════════════════════════════════════════╗" -ForegroundColor Red
        Write-Host "  ║            🔑 API CREDENTIALS CONFIGURATION                 ║" -ForegroundColor Red
        Write-Host "  ╠════════════════════════════════════════════════════════════╣" -ForegroundColor Red
        Write-Host "  ║                                                            ║" -ForegroundColor Red
        Write-Host "  ║  Your API keys are currently set to DEMO placeholders.     ║" -ForegroundColor Yellow
        Write-Host "  ║  AI analysis features will NOT work with these values.     ║" -ForegroundColor Yellow
        Write-Host "  ║                                                            ║" -ForegroundColor Red
        Write-Host "  ╠════════════════════════════════════════════════════════════╣" -ForegroundColor Red
        Write-Host "  ║  Get your API keys from:                                   ║" -ForegroundColor Cyan
        Write-Host "  ║                                                            ║" -ForegroundColor Red
        Write-Host "  ║  • OpenAI:     https://platform.openai.com/api-keys        ║" -ForegroundColor White
        Write-Host "  ║  • Anthropic:  https://console.anthropic.com/              ║" -ForegroundColor White
        Write-Host "  ║  • Gemini:     https://makersuite.google.com/app/apikey    ║" -ForegroundColor White
        Write-Host "  ║  • xAI Grok:   https://console.x.ai/                       ║" -ForegroundColor White
        Write-Host "  ║  • Kimi:       https://platform.moonshot.cn/               ║" -ForegroundColor White
        Write-Host "  ║                                                            ║" -ForegroundColor Red
        Write-Host "  ╚════════════════════════════════════════════════════════════╝" -ForegroundColor Red
        Write-Host ""
        
        # Prompt user to configure now
        Write-Host "  Would you like to configure your API keys now?" -ForegroundColor Cyan
        Write-Host "  [Y] Yes, configure now  [N] Skip (configure later in Settings)" -ForegroundColor White
        Write-Host ""
        Write-Host "  Press Y or N: " -NoNewline -ForegroundColor Cyan
        
        $response = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
        Write-Host ""
        
        if ($response.Character -eq 'Y' -or $response.Character -eq 'y') {
            Write-Host ""
            Invoke-InteractiveCredentialSetup
        } else {
            Write-Host ""
            Write-Host "  ⚠️  Remember to configure your API keys later:" -ForegroundColor Yellow
            Write-Host "     1. Start the app: .\start.ps1" -ForegroundColor Gray
            Write-Host "     2. Open Settings in the app" -ForegroundColor Gray
            Write-Host "     3. Enter your API keys" -ForegroundColor Gray
            Write-Host ""
        }
    }
    
    Show-Progress "Credentials checked" 1
}

function Invoke-InteractiveCredentialSetup {
    Write-Host ""
    Write-Host "  ┌────────────────────────────────────────────────────────────┐" -ForegroundColor Cyan
    Write-Host "  │         API Key Configuration (press Enter to skip)        │" -ForegroundColor Cyan
    Write-Host "  └────────────────────────────────────────────────────────────┘" -ForegroundColor Cyan
    Write-Host ""
    
    $apiKeys = @{}
    
    # OpenAI
    Write-Host "  OpenAI API Key (e.g., sk-proj-...): " -NoNewline -ForegroundColor White
    $openaiKey = Read-Host
    if ($openaiKey) { $apiKeys.OPENAI_API_KEY = $openaiKey }
    
    # Anthropic
    Write-Host "  Anthropic API Key (e.g., sk-ant-...): " -NoNewline -ForegroundColor White
    $anthropicKey = Read-Host
    if ($anthropicKey) { $apiKeys.ANTHROPIC_API_KEY = $anthropicKey }
    
    # Gemini
    Write-Host "  Google Gemini API Key: " -NoNewline -ForegroundColor White
    $geminiKey = Read-Host
    if ($geminiKey) { $apiKeys.GEMINI_API_KEY = $geminiKey }
    
    # Grok
    Write-Host "  xAI Grok API Key: " -NoNewline -ForegroundColor White
    $grokKey = Read-Host
    if ($grokKey) { $apiKeys.GROK_API_KEY = $grokKey }
    
    # Kimi
    Write-Host "  Kimi/Moonshot API Key: " -NoNewline -ForegroundColor White
    $kimiKey = Read-Host
    if ($kimiKey) { $apiKeys.KIMI_API_KEY = $kimiKey }
    
    # Z.ai
    Write-Host "  Z.ai API Key: " -NoNewline -ForegroundColor White
    $zaiKey = Read-Host
    if ($zaiKey) { $apiKeys.ZAI_API_KEY = $zaiKey }
    
    # Update .env file
    if ($apiKeys.Count -gt 0) {
        Write-Host ""
        Write-Host "  Updating .env file..." -ForegroundColor Cyan
        
        $envContent = Get-Content ".env" -Raw -ErrorAction SilentlyContinue
        
        foreach ($key in $apiKeys.Keys) {
            $value = $apiKeys[$key]
            if ($envContent -match "$key=.*") {
                $envContent = $envContent -replace "$key=.*", "$key=`"$value`""
            } else {
                $envContent += "`n$key=`"$value`""
            }
            Write-Host "    ✓ $key updated" -ForegroundColor Green
        }
        
        $envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
        Write-Host ""
        Write-Host "  ✅ API keys saved to .env file" -ForegroundColor Green
    } else {
        Write-Host ""
        Write-Host "  No API keys were entered. You can configure them later in Settings." -ForegroundColor Yellow
    }
}

function Invoke-BuildCheck {
    Show-Progress "Verifying build..."
    
    Write-Log "Running build verification" -Level INFO
    
    try {
        $buildCmd = if ($Script:PackageManager -eq "bun") {
            "bun run build"
        } else {
            "npm run build"
        }
        
        $result = Invoke-Expression "$buildCmd 2>&1"
        
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Build completed successfully" -Level SUCCESS
        } else {
            Write-Log "Build output: $result" -Level DEBUG
            $error = Get-ErrorSolution "E009"
            Add-Error "E009" $error.Message $error.Solution -Fatal $false
        }
    } catch {
        Write-Log "Build check failed: $_" -Level WARN
        Add-Warning "W006" "Build verification failed" "Run 'bun run build' manually to check errors"
    }
    
    Show-Progress "Build verified" 1
}

function Invoke-FinalChecks {
    Show-Progress "Running final checks..."
    
    Write-Log "Performing final checks" -Level INFO
    
    # Verify critical files
    $criticalFiles = @(
        "package.json",
        "prisma\schema.prisma",
        "src\app\page.tsx",
        "src\lib\db.ts"
    )
    
    foreach ($file in $criticalFiles) {
        if (-not (Test-Path $file)) {
            Add-Warning "W007" "Missing file: $file" "Verify the repository was cloned correctly"
        }
    }
    
    # Check if database file exists
    if (Test-Path "prisma\dev.db") {
        Write-Log "Database file found" -Level SUCCESS
    } else {
        Add-Warning "W008" "Database file not found" "Run 'npx prisma migrate dev' to create the database"
    }
    
    Show-Progress "Final checks completed" 1
}

function Show-SuccessMessage {
    Write-Header "Setup Complete!"
    
    Write-Host "  $($Config.AppName) v$($Config.Version)" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Next Steps:" -ForegroundColor White
    Write-Host "  1. Start the development server:" -ForegroundColor Gray
    Write-Host "     .\start.ps1" -ForegroundColor Green
    Write-Host ""
    Write-Host "  2. Or run manually:" -ForegroundColor Gray
    Write-Host "     bun run dev" -ForegroundColor Green
    Write-Host ""
    Write-Host "  3. Open in browser:" -ForegroundColor Gray
    Write-Host "     http://localhost:3000" -ForegroundColor Green
    Write-Host ""
    Write-Host "  4. Configure API keys in Settings (optional)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  Documentation: https://github.com/Shootre21/political-spectrum-app-v2" -ForegroundColor DarkGray
    Write-Host "  Log file: $LogFile" -ForegroundColor DarkGray
    Write-Host ""
}

# ============================================
# MAIN EXECUTION
# ============================================
function Main {
    $startTime = Get-Date
    
    # Initialize log
    try {
        "" | Out-File -FilePath $LogFile -Encoding utf8 -Force
    } catch {
        $LogFile = ".\setup-$(Get-Date -Format 'yyyyMMddHHmmss').log"
    }
    
    Write-Header "$($Config.AppName) Setup v$($Config.Version)"
    
    Write-Log "Starting setup process" -Level INFO
    Write-Log "PowerShell version: $($PSVersionTable.PSVersion)" -Level DEBUG
    Write-Log "Working directory: $PWD" -Level DEBUG
    
    # Calculate total steps
    $totalSteps = 6
    if (-not $SkipDeps) { $totalSteps++ }
    if (-not $SkipDB) { $totalSteps++ }
    if (-not $SkipEnv) { $totalSteps++ }
    Reset-Progress -Total $totalSteps
    
    try {
        # Step 1: Prerequisites
        Invoke-PrerequisitesCheck
        
        # Step 2: Dependencies
        if (-not $SkipDeps) {
            Invoke-DependencyInstall
        }
        
        # Step 3: Database
        if (-not $SkipDB) {
            Invoke-DatabaseSetup
        }
        
        # Step 4: Environment
        if (-not $SkipEnv) {
            Invoke-EnvironmentSetup
        }
        
        # Step 5: Credentials prompt
        Invoke-CredentialsPrompt
        
        # Step 6: Build check
        Invoke-BuildCheck
        
        # Step 7: Final checks
        Invoke-FinalChecks
        
        # Show summary
        Show-ErrorSummary
        
        # Show success message if no fatal errors
        if ($Script:Errors | Where-Object { $_.Fatal }) {
            Write-Host "`n  Setup completed with errors. Please fix the issues above." -ForegroundColor Yellow
        } else {
            Show-SuccessMessage
        }
        
    } catch {
        Write-Host "`n  Setup failed: $_" -ForegroundColor Red
        Write-Log "Setup failed: $_" -Level ERROR
        Show-ErrorSummary
        exit 1
    }
    
    $duration = ((Get-Date) - $startTime).TotalSeconds
    Write-Log "Setup completed in $([Math]::Round($duration, 1)) seconds" -Level INFO
    
    # Write summary to log
    $summary = @"

========================================
SETUP SUMMARY
========================================
Timestamp: $(Get-Date)
Duration: $([Math]::Round($duration, 1)) seconds
Errors: $($Script:Errors.Count)
Warnings: $($Script:Warnings.Count)
Log File: $LogFile
========================================
"@
    
    Add-Content -Path $LogFile -Value $summary
}

# Run main function
Main
