<#
.SYNOPSIS
    Political Spectrum App - One-Click Setup Script
.DESCRIPTION
    Automated setup script for the Political Spectrum App with progress tracking,
    logging, error handling, and troubleshooting capabilities.
.VERSION
    2.9.0 - Auto-update from Git, real-time server monitoring
.AUTHOR
    Shootre21
.REPOSITORY
    https://github.com/Shootre21/political-spectrum-app-v2
#>

#Requires -Version 5.1

param(
    [switch]$SkipDeps,
    [switch]$SkipDB,
    [switch]$SkipEnv,
    [switch]$Force,
    [switch]$Verbose,
    [switch]$NoAutoInstall,  # Skip automatic installation of Node.js/Bun/Git
    [switch]$Start,          # Automatically start the server after setup
    [switch]$NoMonitor,      # Disable real-time monitoring when starting
    [string]$LogFile = ".\setup.log"
)

# ============================================
# CONFIGURATION
# ============================================
$Config = @{
    AppName = "Political Spectrum App"
    Version = "2.9.0"
    NodeMinVersion = "18.0.0"
    BunMinVersion = "1.0.0"
    RequiredPorts = @(3000, 5555)
    # Default demo credentials - USER MUST CHANGE THESE!
    DefaultCredentials = @{
        OPENAI_API_KEY = "sk-demo-REPLACE-WITH-YOUR-KEY"
        ANTHROPIC_API_KEY = "sk-ant-demo-REPLACE-WITH-YOUR-KEY"
        KIMI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        ZAI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        GROK_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
        GEMINI_API_KEY = "demo-REPLACE-WITH-YOUR-KEY"
    }
    EnvTemplate = @'
# Political Spectrum App - Environment Variables
# Generated by setup.ps1
# 
# WARNING: Default demo credentials are set below.
#    You MUST replace these with your actual API keys!
#    Get your keys from:
#    - OpenAI: https://platform.openai.com/api-keys
#    - Anthropic: https://console.anthropic.com/
#    - Google Gemini: https://makersuite.google.com/app/apikey
#    - xAI Grok: https://console.x.ai/
#    - Kimi: https://platform.moonshot.cn/
#    - Z.ai: Contact Z.ai for API access

# Database
DATABASE_URL="file:./dev.db"

# AI Provider API Keys (REPLACE THESE WITH YOUR ACTUAL KEYS!)
OPENAI_API_KEY="sk-demo-REPLACE-WITH-YOUR-KEY"
ANTHROPIC_API_KEY="sk-ant-demo-REPLACE-WITH-YOUR-KEY"
KIMI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
ZAI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
GROK_API_KEY="demo-REPLACE-WITH-YOUR-KEY"
GEMINI_API_KEY="demo-REPLACE-WITH-YOUR-KEY"

# Site URL for SEO
NEXT_PUBLIC_SITE_URL="http://localhost:3000"
'@
}

# ============================================
# LOGGING SYSTEM
# ============================================
function Write-Log {
    param(
        [string]$Message,
        [ValidateSet('INFO', 'WARN', 'ERROR', 'SUCCESS', 'DEBUG')]
        [string]$Level = 'INFO'
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logEntry = "[$timestamp] [$Level] $Message"
    
    # Write to log file
    try {
        Add-Content -Path $LogFile -Value $logEntry -ErrorAction SilentlyContinue
    } catch {}
    
    # Console output with colors
    switch ($Level) {
        'INFO'    { Write-Host $logEntry -ForegroundColor Cyan }
        'WARN'    { Write-Host $logEntry -ForegroundColor Yellow }
        'ERROR'   { Write-Host $logEntry -ForegroundColor Red }
        'SUCCESS' { Write-Host $logEntry -ForegroundColor Green }
        'DEBUG'   { if ($Verbose) { Write-Host $logEntry -ForegroundColor Gray } }
    }
}

function Write-Header {
    param([string]$Title)
    
    $width = 60
    $padding = [Math]::Max(0, ($width - $Title.Length) / 2)
    
    Write-Host ""
    Write-Host ("=" * $width) -ForegroundColor DarkCyan
    Write-Host (" " * [Math]::Floor($padding) + $Title) -ForegroundColor Cyan
    Write-Host ("=" * $width) -ForegroundColor DarkCyan
    Write-Host ""
}

# ============================================
# PROGRESS BAR SYSTEM
# ============================================
$Script:Progress = @{
    Current = 0
    Total = 10
    Activity = "Setting up Political Spectrum App"
}

function Show-Progress {
    param(
        [string]$Status,
        [int]$Increment = 1
    )
    
    $Script:Progress.Current += $Increment
    $percent = [Math]::Min(100, [Math]::Round(($Script:Progress.Current / $Script:Progress.Total) * 100))
    
    # Create progress bar string
    $barWidth = 30
    $filled = [Math]::Round($barWidth * ($percent / 100))
    $empty = $barWidth - $filled
    $bar = "[" + ("=" * $filled) + (" " * $empty) + "]"
    
    Write-Host "`r$bar $percent% - $Status" -NoNewline -ForegroundColor Yellow
    
    if ($Script:Progress.Current -ge $Script:Progress.Total) {
        Write-Host ""
    }
}

function Reset-Progress {
    param([int]$Total = 10)
    $Script:Progress.Current = 0
    $Script:Progress.Total = $Total
}

# ============================================
# ERROR HANDLING SYSTEM
# ============================================
$Script:Errors = @()
$Script:Warnings = @()

function Add-Error {
    param(
        [string]$Code,
        [string]$Message,
        [string]$Solution,
        [bool]$Fatal = $false
    )
    
    $errorObj = @{
        Code = $Code
        Message = $Message
        Solution = $Solution
        Fatal = $Fatal
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    $Script:Errors += $errorObj
    Write-Log $Message -Level ERROR
    
    if ($Fatal) {
        Show-ErrorSummary
        throw "Fatal error occurred: $Message"
    }
}

function Add-Warning {
    param(
        [string]$Code,
        [string]$Message,
        [string]$Solution
    )
    
    $warningObj = @{
        Code = $Code
        Message = $Message
        Solution = $Solution
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    $Script:Warnings += $warningObj
    Write-Log $Message -Level WARN
}

function Show-ErrorSummary {
    Write-Header "Setup Summary"
    
    if ($Script:Errors.Count -eq 0 -and $Script:Warnings.Count -eq 0) {
        Write-Host "  [OK] No errors or warnings encountered!" -ForegroundColor Green
        return
    }
    
    if ($Script:Errors.Count -gt 0) {
        Write-Host "`n  ERRORS ($($Script:Errors.Count)):" -ForegroundColor Red
        foreach ($err in $Script:Errors) {
            Write-Host "    [$($err.Code)] $($err.Message)" -ForegroundColor Red
            Write-Host "           Solution: $($err.Solution)" -ForegroundColor Yellow
        }
    }
    
    if ($Script:Warnings.Count -gt 0) {
        Write-Host "`n  WARNINGS ($($Script:Warnings.Count)):" -ForegroundColor Yellow
        foreach ($warn in $Script:Warnings) {
            Write-Host "    [$($warn.Code)] $($warn.Message)" -ForegroundColor Yellow
            Write-Host "           Solution: $($warn.Solution)" -ForegroundColor Cyan
        }
    }
    
    Write-Host ""
}

# ============================================
# COMMON ERROR DEFINITIONS
# ============================================
$ErrorCodes = @{
    E001 = @{
        Message = "Node.js is not installed and auto-install failed"
        Solution = "Install Node.js 18+ manually from https://nodejs.org or run: winget install OpenJS.NodeJS.LTS"
    }
    E002 = @{
        Message = "Node.js version is too old and upgrade failed"
        Solution = "Update Node.js to version 18 or higher from https://nodejs.org"
    }
    E003 = @{
        Message = "Bun is not installed and auto-install failed"
        Solution = "Install Bun manually from https://bun.sh or run: powershell -c 'irm bun.sh/install.ps1 | iex'"
    }
    E004 = @{
        Message = "Port 3000 is already in use"
        Solution = "Stop the process using port 3000: Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess | Stop-Process -Force"
    }
    E005 = @{
        Message = "Package installation failed"
        Solution = "Try: Remove-Item node_modules -Recurse -Force; bun install"
    }
    E006 = @{
        Message = "Database migration failed"
        Solution = "Try: npx prisma migrate reset --force"
    }
    E007 = @{
        Message = "Prisma client generation failed"
        Solution = "Try: npx prisma generate"
    }
    E008 = @{
        Message = "Environment file creation failed"
        Solution = "Create .env file manually with DATABASE_URL='file:./dev.db'"
    }
    E009 = @{
        Message = "Build failed"
        Solution = "Check error logs and ensure all dependencies are installed"
    }
    E010 = @{
        Message = "Git is not installed"
        Solution = "Install Git from https://git-scm.com or run: winget install Git.Git"
    }
    E011 = @{
        Message = "Insufficient disk space"
        Solution = "Free up at least 500MB of disk space"
    }
    E012 = @{
        Message = "Permission denied"
        Solution = "Run PowerShell as Administrator or check folder permissions"
    }
    E013 = @{
        Message = "Network connection failed"
        Solution = "Check your internet connection and proxy settings"
    }
    E014 = @{
        Message = "Prisma CLI not found"
        Solution = "Run: bun add prisma @prisma/client"
    }
    E015 = @{
        Message = "SQLite database locked"
        Solution = "Close any applications using the database and try again"
    }
}

function Get-ErrorSolution {
    param([string]$Code)
    
    if ($ErrorCodes.ContainsKey($Code)) {
        return $ErrorCodes[$Code]
    }
    return @{ Message = "Unknown error"; Solution = "Check the documentation or GitHub issues" }
}

# ============================================
# AUTO-INSTALL SYSTEM
# ============================================
function Install-NodeJS {
    param([switch]$Force)
    
    Write-Log "Attempting to install Node.js automatically..." -Level INFO
    Write-Host ""
    Write-Host "  [INSTALL] Installing Node.js LTS..." -ForegroundColor Cyan
    
    # Check if winget is available
    if (Test-CommandExists "winget") {
        try {
            Write-Host "  Using winget to install Node.js LTS..." -ForegroundColor Gray
            
            # Install Node.js LTS using winget
            $installResult = winget install OpenJS.NodeJS.LTS --accept-source-agreements --accept-package-agreements 2>&1
            
            if ($LASTEXITCODE -eq 0) {
                Write-Log "Node.js installed successfully via winget" -Level SUCCESS
                Write-Host "  [OK] Node.js installed successfully!" -ForegroundColor Green
                
                # Refresh environment variables
                $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
                
                # Also try to refresh the current session
                $nodePaths = @(
                    "$env:ProgramFiles\nodejs",
                    "$env:ProgramFiles(x86)\nodejs",
                    "$env:LOCALAPPDATA\Programs\nodejs"
                )
                
                foreach ($nodePath in $nodePaths) {
                    if (Test-Path $nodePath) {
                        $env:Path = "$nodePath;$env:Path"
                        break
                    }
                }
                
                # Verify installation
                $newVersion = Get-NodeVersion
                if ($newVersion) {
                    Write-Host "  Node.js version: $newVersion" -ForegroundColor Green
                    return $true
                } else {
                    Write-Host "  Node.js installed but not in PATH. Please restart PowerShell and run setup again." -ForegroundColor Yellow
                    Write-Host "  Alternatively, you may need to restart your computer for PATH changes to take effect." -ForegroundColor Yellow
                    return $false
                }
            } else {
                Write-Log "Winget installation failed: $installResult" -Level WARN
            }
        } catch {
            Write-Log "Winget installation error: $_" -Level WARN
        }
    }
    
    # Fallback: Download and install Node.js using Chocolatey or direct download
    if (Test-CommandExists "choco") {
        try {
            Write-Host "  Using Chocolatey to install Node.js LTS..." -ForegroundColor Gray
            choco install nodejs-lts -y
            
            # Refresh environment
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
            
            $newVersion = Get-NodeVersion
            if ($newVersion) {
                Write-Host "  [OK] Node.js installed via Chocolatey!" -ForegroundColor Green
                return $true
            }
        } catch {
            Write-Log "Chocolatey installation failed: $_" -Level WARN
        }
    }
    
    # Final fallback: Direct download using PowerShell
    Write-Host "  Attempting direct download installation..." -ForegroundColor Yellow
    
    try {
        # Get the latest LTS version info
        $nodeApiUrl = "https://nodejs.org/dist/index.json"
        $nodeVersions = Invoke-RestMethod -Uri $nodeApiUrl -UseBasicParsing
        $ltsVersion = ($nodeVersions | Where-Object { $_.lts -ne $false } | Select-Object -First 1).version
        
        if (-not $ltsVersion) {
            $ltsVersion = "v20.11.0"  # Fallback version
        }
        
        Write-Host "  Downloading Node.js $ltsVersion..." -ForegroundColor Gray
        
        # Determine architecture
        $arch = if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" }
        $msiUrl = "https://nodejs.org/dist/$ltsVersion/node-$ltsVersion-$arch.msi"
        $msiPath = "$env:TEMP\nodejs-installer.msi"
        
        # Download MSI
        Invoke-WebRequest -Uri $msiUrl -OutFile $msiPath -UseBasicParsing
        
        # Install silently
        Write-Host "  Installing Node.js (this may take a moment)..." -ForegroundColor Gray
        $msiArgs = "/i `"$msiPath`" /qn /norestart ADDLOCAL=ALL"
        $msiProcess = Start-Process msiexec.exe -ArgumentList $msiArgs -Wait -PassThru
        
        if ($msiProcess.ExitCode -eq 0) {
            Write-Host "  [OK] Node.js installed successfully!" -ForegroundColor Green
            
            # Refresh PATH
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
            
            # Clean up
            Remove-Item $msiPath -Force -ErrorAction SilentlyContinue
            
            return $true
        } else {
            Write-Host "  [ERROR] MSI installation failed with exit code: $($msiProcess.ExitCode)" -ForegroundColor Red
        }
    } catch {
        Write-Log "Direct download installation failed: $_" -Level ERROR
        Write-Host "  [ERROR] Failed to install Node.js automatically: $_" -ForegroundColor Red
    }
    
    return $false
}

function Install-Bun {
    Write-Log "Attempting to install Bun automatically..." -Level INFO
    Write-Host ""
    Write-Host "  [INSTALL] Installing Bun..." -ForegroundColor Cyan
    
    try {
        # Use the official Bun installer
        Write-Host "  Downloading and installing Bun..." -ForegroundColor Gray
        
        $installScript = Invoke-RestMethod -Uri "https://bun.sh/install.ps1" -UseBasicParsing
        $installScriptPath = "$env:TEMP\bun-install.ps1"
        $installScript | Out-File -FilePath $installScriptPath -Encoding UTF8
        
        # Run the installer
        $installResult = & powershell.exe -ExecutionPolicy Bypass -File $installScriptPath 2>&1
        
        # Refresh PATH
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "User") + ";" + $env:Path
        
        # Add Bun path if it exists
        $bunPath = "$env:USERPROFILE\.bun\bin"
        if (Test-Path $bunPath) {
            $env:Path = "$bunPath;$env:Path"
        }
        
        # Verify installation
        if (Test-CommandExists "bun") {
            $bunVersion = bun --version
            Write-Host "  [OK] Bun installed successfully! Version: $bunVersion" -ForegroundColor Green
            Write-Log "Bun installed successfully: $bunVersion" -Level SUCCESS
            return $true
        } else {
            Write-Host "  [WARN] Bun installed but needs PATH refresh. Restart PowerShell to use Bun." -ForegroundColor Yellow
            return $false
        }
    } catch {
        Write-Log "Bun installation failed: $_" -Level WARN
        Write-Host "  [WARN] Could not install Bun automatically. Falling back to npm." -ForegroundColor Yellow
        return $false
    }
}

function Install-Git {
    Write-Log "Attempting to install Git automatically..." -Level INFO
    Write-Host ""
    Write-Host "  [INSTALL] Installing Git..." -ForegroundColor Cyan
    
    if (Test-CommandExists "winget") {
        try {
            winget install Git.Git --accept-source-agreements --accept-package-agreements 2>&1 | Out-Null
            
            # Refresh PATH
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
            
            if (Test-CommandExists "git") {
                Write-Host "  [OK] Git installed successfully!" -ForegroundColor Green
                return $true
            }
        } catch {
            Write-Log "Git installation via winget failed: $_" -Level WARN
        }
    }
    
    Write-Host "  [WARN] Could not install Git automatically." -ForegroundColor Yellow
    return $false
}

# ============================================
# SYSTEM CHECKS
# ============================================
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-CommandExists {
    param([string]$Command)
    return $null -ne (Get-Command $Command -ErrorAction SilentlyContinue)
}

function Test-PortAvailable {
    param([int]$Port)
    $connection = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue
    return $null -eq $connection
}

function Get-NodeVersion {
    if (Test-CommandExists "node") {
        $version = node --version
        return $version -replace 'v', ''
    }
    return $null
}

function Compare-Versions {
    param([string]$V1, [string]$V2)
    
    $v1Parts = $V1.Split('.')
    $v2Parts = $V2.Split('.')
    
    for ($i = 0; $i -lt [Math]::Max($v1Parts.Length, $v2Parts.Length); $i++) {
        $v1Num = if ($i -lt $v1Parts.Length) { [int]$v1Parts[$i] } else { 0 }
        $v2Num = if ($i -lt $v2Parts.Length) { [int]$v2Parts[$i] } else { 0 }
        
        if ($v1Num -gt $v2Num) { return 1 }
        if ($v1Num -lt $v2Num) { return -1 }
    }
    return 0
}

function Test-DiskSpace {
    param([string]$Path, [long]$RequiredMB = 500)
    
    try {
        $drive = (Get-Item $Path -ErrorAction SilentlyContinue).PSDrive
        if (-not $drive) {
            $drive = Get-PSDrive -Name $Path.Substring(0,1)
        }
        $freeSpaceMB = [Math]::Round($drive.Free / 1MB, 2)
        return $freeSpaceMB -ge $RequiredMB
    } catch {
        return $true  # Assume OK if can't check
    }
}

# ============================================
# SETUP STEPS
# ============================================
function Invoke-PrerequisitesCheck {
    Show-Progress "Checking prerequisites..."
    
    Write-Log "Starting prerequisites check" -Level INFO
    
    # Check if running as admin (warn but don't fail)
    if (-not (Test-Administrator)) {
        Add-Warning "W001" "Not running as Administrator" "Some features may require elevated permissions"
    }
    
    # Check disk space
    if (-not (Test-DiskSpace $PWD)) {
        $error = Get-ErrorSolution "E011"
        Add-Error "E011" $error.Message $error.Solution -Fatal $false
    }
    
    # Check Node.js - AUTO-INSTALL IF MISSING (unless -NoAutoInstall is specified)
    $nodeVersion = Get-NodeVersion
    if (-not $nodeVersion) {
        if ($NoAutoInstall) {
            Write-Host ""
            Write-Host "  [ERROR] Node.js is not installed and auto-install is disabled." -ForegroundColor Red
            Write-Host "  Install Node.js 18+ from: https://nodejs.org" -ForegroundColor Red
            Write-Host "  Or run: winget install OpenJS.NodeJS.LTS" -ForegroundColor Red
            Write-Host ""
            $error = Get-ErrorSolution "E001"
            Add-Error "E001" $error.Message $error.Solution -Fatal $true
        }
        
        Write-Host ""
        Write-Host "  ============================================================" -ForegroundColor Yellow
        Write-Host "  Node.js is not installed. Auto-installing..." -ForegroundColor Yellow
        Write-Host "  ============================================================" -ForegroundColor Yellow
        
        $installed = Install-NodeJS
        
        if (-not $installed) {
            # Try one more time after refreshing PATH
            $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
            Start-Sleep -Seconds 2
            
            $nodeVersion = Get-NodeVersion
            if (-not $nodeVersion) {
                Write-Host ""
                Write-Host "  [ERROR] Failed to install Node.js automatically." -ForegroundColor Red
                Write-Host "  Please install Node.js manually from: https://nodejs.org" -ForegroundColor Red
                Write-Host "  Or run: winget install OpenJS.NodeJS.LTS" -ForegroundColor Red
                Write-Host ""
                $error = Get-ErrorSolution "E001"
                Add-Error "E001" $error.Message $error.Solution -Fatal $true
            }
        } else {
            # Re-check version after installation
            $nodeVersion = Get-NodeVersion
        }
    }
    
    # Verify Node.js version is sufficient
    if ($nodeVersion -and (Compare-Versions $nodeVersion $Config.NodeMinVersion) -lt 0) {
        if ($NoAutoInstall) {
            Write-Host ""
            Write-Host "  [ERROR] Node.js version $nodeVersion is too old. Required: $($Config.NodeMinVersion)+" -ForegroundColor Red
            $error = Get-ErrorSolution "E002"
            Add-Error "E002" "$($error.Message) (Current: $nodeVersion, Required: $($Config.NodeMinVersion))" $error.Solution -Fatal $true
        }
        
        Write-Host ""
        Write-Host "  Node.js version $nodeVersion is too old. Required: $($Config.NodeMinVersion)+" -ForegroundColor Yellow
        Write-Host "  Upgrading Node.js..." -ForegroundColor Yellow
        
        $installed = Install-NodeJS -Force
        $nodeVersion = Get-NodeVersion
        
        if (-not $nodeVersion -or (Compare-Versions $nodeVersion $Config.NodeMinVersion) -lt 0) {
            $error = Get-ErrorSolution "E002"
            Add-Error "E002" "$($error.Message) (Current: $nodeVersion, Required: $($Config.NodeMinVersion))" $error.Solution -Fatal $true
        }
    }
    
    Write-Log "Node.js version: $nodeVersion" -Level SUCCESS
    Write-Host "  [OK] Node.js version: $nodeVersion" -ForegroundColor Green
    
    # Check Bun (preferred) - AUTO-INSTALL IF MISSING (unless -NoAutoInstall is specified)
    if (-not (Test-CommandExists "bun")) {
        if ($NoAutoInstall) {
            # Check if npm is available as fallback
            if (-not (Test-CommandExists "npm")) {
                Write-Host ""
                Write-Host "  [ERROR] Neither Bun nor npm is available!" -ForegroundColor Red
                $error = Get-ErrorSolution "E003"
                Add-Error "E003" "Neither Bun nor npm is available" $error.Solution -Fatal $true
            }
            Write-Host "  Using npm as package manager (Bun not installed)" -ForegroundColor Yellow
            $Script:PackageManager = "npm"
        } else {
            Write-Host ""
            Write-Host "  Bun is not installed. Auto-installing for faster performance..." -ForegroundColor Cyan
            
            $bunInstalled = Install-Bun
            
            if (-not $bunInstalled) {
                # Check if npm is available as fallback
                if (-not (Test-CommandExists "npm")) {
                    Write-Host ""
                    Write-Host "  [ERROR] Neither Bun nor npm is available!" -ForegroundColor Red
                    $error = Get-ErrorSolution "E003"
                    Add-Error "E003" "Neither Bun nor npm is available" $error.Solution -Fatal $true
                } else {
                    Write-Host "  Using npm as package manager (Bun installation failed)" -ForegroundColor Yellow
                    $Script:PackageManager = "npm"
                }
            } else {
                $Script:PackageManager = "bun"
                Write-Log "Using Bun as package manager" -Level SUCCESS
            }
        }
    } else {
        $Script:PackageManager = "bun"
        $bunVersion = bun --version
        Write-Log "Using Bun as package manager (version: $bunVersion)" -Level SUCCESS
        Write-Host "  [OK] Bun version: $bunVersion" -ForegroundColor Green
    }
    
    # Check Git - AUTO-INSTALL IF MISSING (unless -NoAutoInstall is specified)
    if (-not (Test-CommandExists "git")) {
        if ($NoAutoInstall) {
            Add-Warning "W003" "Git is not installed" "Required for version control: winget install Git.Git"
        } else {
            Write-Host ""
            Write-Host "  Git is not installed. Auto-installing..." -ForegroundColor Cyan
            
            $gitInstalled = Install-Git
            
            if ($gitInstalled) {
                Write-Host "  [OK] Git installed successfully" -ForegroundColor Green
            } else {
                Add-Warning "W003" "Git installation failed" "Required for version control: winget install Git.Git"
            }
        }
    } else {
        $gitVersion = git --version 2>&1
        Write-Host "  [OK] Git: $gitVersion" -ForegroundColor Green
    }
    
    # Check ports
    foreach ($port in $Config.RequiredPorts) {
        if (-not (Test-PortAvailable $port)) {
            $error = Get-ErrorSolution "E004"
            Add-Warning "W004" "Port $port is already in use" $error.Solution
        }
    }
    
    Show-Progress "Prerequisites checked" 1
    return $true
}

function Invoke-DependencyInstall {
    Show-Progress "Installing dependencies..."
    
    Write-Log "Starting dependency installation" -Level INFO
    
    # Clean install if Force flag or node_modules missing
    if ($Force -or -not (Test-Path "node_modules")) {
        if (Test-Path "node_modules") {
            Write-Log "Removing existing node_modules..." -Level INFO
            Remove-Item "node_modules" -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    
    # Install dependencies
    $installCmd = if ($Script:PackageManager -eq "bun") {
        "bun install"
    } else {
        "npm install"
    }
    
    Write-Log "Running: $installCmd" -Level DEBUG
    
    try {
        $result = Invoke-Expression "$installCmd 2>&1"
        if ($LASTEXITCODE -ne 0) {
            $error = Get-ErrorSolution "E005"
            Add-Error "E005" $error.Message $error.Solution -Fatal $false
            Write-Log "Install output: $result" -Level DEBUG
            
            # Retry with npm if bun failed
            if ($Script:PackageManager -eq "bun") {
                Write-Log "Retrying with npm..." -Level WARN
                npm install
                if ($LASTEXITCODE -ne 0) {
                    Add-Error "E005" "Package installation failed after retry" $error.Solution -Fatal $true
                }
            }
        }
        
        Write-Log "Dependencies installed successfully" -Level SUCCESS
    } catch {
        $error = Get-ErrorSolution "E005"
        Add-Error "E005" "$($error.Message): $_" $error.Solution -Fatal $true
    }
    
    Show-Progress "Dependencies installed" 1
}

function Invoke-DatabaseSetup {
    Show-Progress "Setting up database..."
    
    Write-Log "Starting database setup" -Level INFO
    
    # Ensure prisma is available
    if (-not (Test-Path "node_modules\.bin\prisma") -and -not (Test-CommandExists "prisma")) {
        Add-Warning "W005" "Prisma CLI not found" "Installing Prisma..."
        
        if ($Script:PackageManager -eq "bun") {
            bun add prisma @prisma/client
        } else {
            npm install prisma @prisma/client
        }
    }
    
    # Generate Prisma client
    Write-Log "Generating Prisma client..." -Level INFO
    try {
        npx prisma generate 2>&1 | Out-Null
        Write-Log "Prisma client generated" -Level SUCCESS
    } catch {
        $error = Get-ErrorSolution "E007"
        Add-Error "E007" $error.Message $error.Solution -Fatal $false
    }
    
    # Run migrations
    Write-Log "Running database migrations..." -Level INFO
    
    if (-not (Test-Path "prisma\dev.db")) {
        try {
            npx prisma migrate dev --name init 2>&1 | Out-Null
            Write-Log "Database migrations completed" -Level SUCCESS
        } catch {
            # Try push if migrate fails
            Write-Log "Migration failed, trying db push..." -Level WARN
            try {
                npx prisma db push 2>&1 | Out-Null
                Write-Log "Database schema pushed successfully" -Level SUCCESS
            } catch {
                $error = Get-ErrorSolution "E006"
                Add-Error "E006" $error.Message $error.Solution -Fatal $false
            }
        }
    } else {
        Write-Log "Database already exists, skipping migration" -Level INFO
    }
    
    Show-Progress "Database configured" 1
}

function Invoke-EnvironmentSetup {
    Show-Progress "Configuring environment..."
    
    Write-Log "Setting up environment" -Level INFO
    
    $envFile = ".env"
    $envLocalFile = ".env.local"
    
    # Create .env if missing
    if (-not (Test-Path $envFile)) {
        try {
            $Config.EnvTemplate | Out-File -FilePath $envFile -Encoding utf8
            Write-Log "Created .env file with default credentials" -Level SUCCESS
            
            # Show warning about default credentials
            Write-Host ""
            Write-Host "  WARNING: Default demo credentials have been set!" -ForegroundColor Yellow
            Write-Host "  --------------------------------------------------" -ForegroundColor DarkYellow
            Write-Host "  The following API keys are placeholders and will NOT work:" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "    * OPENAI_API_KEY = 'sk-demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host "    * ANTHROPIC_API_KEY = 'sk-ant-demo-REPLACE...'" -ForegroundColor DarkYellow
            Write-Host "    * GEMINI_API_KEY = 'demo-REPLACE-WITH-YOUR-KEY'" -ForegroundColor DarkYellow
            Write-Host ""
            Write-Host "  You MUST replace these with your actual API keys!" -ForegroundColor Yellow
            Write-Host ""
        } catch {
            $error = Get-ErrorSolution "E008"
            Add-Error "E008" $error.Message $error.Solution -Fatal $false
        }
    } else {
        Write-Log ".env file already exists" -Level INFO
        
        # Check if default credentials are still present
        $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
        if ($envContent -match "sk-demo-REPLACE" -or $envContent -match "demo-REPLACE") {
            Write-Host ""
            Write-Host "  WARNING: Default demo credentials detected!" -ForegroundColor Yellow
            Write-Host "  --------------------------------------------------" -ForegroundColor DarkYellow
            Write-Host "  Your .env file contains placeholder API keys." -ForegroundColor Yellow
            Write-Host "  AI analysis features will NOT work until you replace them." -ForegroundColor Yellow
            Write-Host ""
        }
    }
    
    # Create .env.local if missing
    if (-not (Test-Path $envLocalFile)) {
        try {
            "# Local environment overrides`n# Add your actual API keys here to override the demo values" | Out-File -FilePath $envLocalFile -Encoding utf8
            Write-Log "Created .env.local file" -Level SUCCESS
        } catch {
            Write-Log "Could not create .env.local" -Level WARN
        }
    }
    
    # Verify DATABASE_URL
    $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
    if ($envContent -notmatch "DATABASE_URL") {
        Add-Content -Path $envFile -Value 'DATABASE_URL="file:./dev.db"'
        Write-Log "Added DATABASE_URL to .env" -Level INFO
    }
    
    Show-Progress "Environment configured" 1
}

function Invoke-CredentialsPrompt {
    Show-Progress "Checking API credentials..."
    
    Write-Log "Checking API credentials status" -Level INFO
    
    $envFile = ".env"
    if (-not (Test-Path $envFile)) {
        return
    }
    
    $envContent = Get-Content $envFile -Raw -ErrorAction SilentlyContinue
    
    # Check for demo credentials
    $hasDemoCreds = $envContent -match "sk-demo-REPLACE" -or $envContent -match "demo-REPLACE"
    
    if ($hasDemoCreds) {
        Write-Host ""
        Write-Host "  +============================================================+" -ForegroundColor Red
        Write-Host "  |            [KEY] API CREDENTIALS CONFIGURATION              |" -ForegroundColor Red
        Write-Host "  +============================================================+" -ForegroundColor Red
        Write-Host "  |                                                            |" -ForegroundColor Red
        Write-Host "  |  Your API keys are currently set to DEMO placeholders.     |" -ForegroundColor Yellow
        Write-Host "  |  AI analysis features will NOT work with these values.     |" -ForegroundColor Yellow
        Write-Host "  |                                                            |" -ForegroundColor Red
        Write-Host "  +============================================================+" -ForegroundColor Red
        Write-Host "  |  Get your API keys from:                                   |" -ForegroundColor Cyan
        Write-Host "  |                                                            |" -ForegroundColor Red
        Write-Host "  |  * OpenAI:     https://platform.openai.com/api-keys        |" -ForegroundColor White
        Write-Host "  |  * Anthropic:  https://console.anthropic.com/              |" -ForegroundColor White
        Write-Host "  |  * Gemini:     https://makersuite.google.com/app/apikey    |" -ForegroundColor White
        Write-Host "  |  * xAI Grok:   https://console.x.ai/                       |" -ForegroundColor White
        Write-Host "  |  * Kimi:       https://platform.moonshot.cn/               |" -ForegroundColor White
        Write-Host "  |                                                            |" -ForegroundColor Red
        Write-Host "  +============================================================+" -ForegroundColor Red
        Write-Host ""
        
        # Prompt user to configure now
        Write-Host "  Would you like to configure your API keys now?" -ForegroundColor Cyan
        Write-Host "  [Y] Yes, configure now  [N] Skip (configure later in Settings)" -ForegroundColor White
        Write-Host ""
        
        # Use Read-Host for reliable input
        $response = Read-Host "  Enter Y or N"
        
        if ($response -eq 'Y' -or $response -eq 'y') {
            Write-Host ""
            Invoke-InteractiveCredentialSetup
        } else {
            Write-Host ""
            Write-Host "  [!] Remember to configure your API keys later:" -ForegroundColor Yellow
            Write-Host "     1. Start the app: .\start.ps1" -ForegroundColor Gray
            Write-Host "     2. Open Settings in the app" -ForegroundColor Gray
            Write-Host "     3. Enter your API keys" -ForegroundColor Gray
            Write-Host ""
        }
    }
    
    Show-Progress "Credentials checked" 1
}

function Invoke-InteractiveCredentialSetup {
    Write-Host ""
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor Cyan
    Write-Host "  |         API Key Configuration (press Enter to skip)        |" -ForegroundColor Cyan
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor Cyan
    Write-Host ""
    
    $apiKeys = @{}
    
    # OpenAI
    Write-Host "  OpenAI API Key (e.g., sk-proj-...): " -NoNewline -ForegroundColor White
    $openaiKey = Read-Host
    if ($openaiKey) { $apiKeys.OPENAI_API_KEY = $openaiKey }
    
    # Anthropic
    Write-Host "  Anthropic API Key (e.g., sk-ant-...): " -NoNewline -ForegroundColor White
    $anthropicKey = Read-Host
    if ($anthropicKey) { $apiKeys.ANTHROPIC_API_KEY = $anthropicKey }
    
    # Gemini
    Write-Host "  Google Gemini API Key: " -NoNewline -ForegroundColor White
    $geminiKey = Read-Host
    if ($geminiKey) { $apiKeys.GEMINI_API_KEY = $geminiKey }
    
    # Grok
    Write-Host "  xAI Grok API Key: " -NoNewline -ForegroundColor White
    $grokKey = Read-Host
    if ($grokKey) { $apiKeys.GROK_API_KEY = $grokKey }
    
    # Kimi
    Write-Host "  Kimi/Moonshot API Key: " -NoNewline -ForegroundColor White
    $kimiKey = Read-Host
    if ($kimiKey) { $apiKeys.KIMI_API_KEY = $kimiKey }
    
    # Z.ai
    Write-Host "  Z.ai API Key: " -NoNewline -ForegroundColor White
    $zaiKey = Read-Host
    if ($zaiKey) { $apiKeys.ZAI_API_KEY = $zaiKey }
    
    # Update .env file
    if ($apiKeys.Count -gt 0) {
        Write-Host ""
        Write-Host "  Updating .env file..." -ForegroundColor Cyan
        
        $envContent = Get-Content ".env" -Raw -ErrorAction SilentlyContinue
        
        foreach ($key in $apiKeys.Keys) {
            $value = $apiKeys[$key]
            if ($envContent -match "$key=.*") {
                $envContent = $envContent -replace "$key=.*", "$key=`"$value`""
            } else {
                $envContent += "`n$key=`"$value`""
            }
            Write-Host "    [OK] $key updated" -ForegroundColor Green
        }
        
        $envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
        Write-Host ""
        Write-Host "  API keys saved to .env file" -ForegroundColor Green
    } else {
        Write-Host ""
        Write-Host "  No API keys were entered. You can configure them later in Settings." -ForegroundColor Yellow
    }
}

function Invoke-BuildCheck {
    Show-Progress "Verifying build..."
    
    Write-Log "Running build verification" -Level INFO
    
    try {
        $buildCmd = if ($Script:PackageManager -eq "bun") {
            "bun run build"
        } else {
            "npm run build"
        }
        
        Write-Host "  Running: $buildCmd" -ForegroundColor Gray
        
        # Capture build output and show in real-time
        $buildOutput = & cmd /c "$buildCmd 2>&1"
        
        if ($LASTEXITCODE -eq 0) {
            Write-Log "Build completed successfully" -Level SUCCESS
            Write-Host "  [OK] Build completed successfully" -ForegroundColor Green
        } else {
            Write-Host "" 
            Write-Host "  ============================================================" -ForegroundColor Red
            Write-Host "  BUILD FAILED - Errors below:" -ForegroundColor Red
            Write-Host "  ============================================================" -ForegroundColor Red
            Write-Host ""
            
            # Show last 20 lines of build output
            $outputLines = $buildOutput -split "`n" | Where-Object { $_.Trim() -ne "" }
            $lastLines = $outputLines | Select-Object -Last 20
            
            foreach ($line in $lastLines) {
                if ($line -match "error|Error|ERROR") {
                    Write-Host "  $line" -ForegroundColor Red
                } elseif ($line -match "warn|Warn|WARN") {
                    Write-Host "  $line" -ForegroundColor Yellow
                } else {
                    Write-Host "  $line" -ForegroundColor Gray
                }
            }
            Write-Host ""
            
            Write-Log "Build failed. Check output above." -Level ERROR
            Add-Warning "W006" "Build verification failed" "Check errors above or run 'bun run build' manually"
        }
    } catch {
        Write-Log "Build check failed: $_" -Level WARN
        Add-Warning "W006" "Build verification failed" "Run 'bun run build' manually to check errors"
    }
    
    Show-Progress "Build verified" 1
}

function Invoke-FinalChecks {
    Show-Progress "Running final checks..."
    
    Write-Log "Performing final checks" -Level INFO
    
    # Verify critical files
    $criticalFiles = @(
        "package.json",
        "prisma\schema.prisma",
        "src\app\page.tsx",
        "src\lib\db.ts"
    )
    
    foreach ($file in $criticalFiles) {
        if (-not (Test-Path $file)) {
            Add-Warning "W007" "Missing file: $file" "Verify the repository was cloned correctly"
        }
    }
    
    # Check if database file exists (check multiple locations)
    $dbPaths = @(
        "prisma\dev.db",
        "prisma\prod.db",
        "db\custom.db",
        "dev.db"
    )
    
    $dbFound = $false
    foreach ($dbPath in $dbPaths) {
        if (Test-Path $dbPath) {
            Write-Log "Database file found: $dbPath" -Level SUCCESS
            $dbFound = $true
            break
        }
    }
    
    if (-not $dbFound) {
        # Database might still be created by Prisma, just log info
        Write-Log "Database file will be created on first run" -Level INFO
    }
    
    Show-Progress "Final checks completed" 1
}

# ============================================
# SERVER MANAGEMENT
# ============================================
$Script:ServerProcess = $null
$Script:ServerLogPath = ".\server.log"
$Script:LastCommitHash = $null
$Script:Restarting = $false
$Script:UpdateInterval = 10  # Check for updates every 10 seconds

# Git Update Functions
function Get-GitCurrentBranch {
    try {
        $branch = git rev-parse --abbrev-ref HEAD 2>$null
        return $branch.Trim()
    } catch {
        return "master"
    }
}

function Get-GitLocalHash {
    try {
        $hash = git rev-parse HEAD 2>$null
        return $hash.Trim()
    } catch {
        return $null
    }
}

function Get-GitRemoteHash {
    param([string]$Branch = "master")
    
    try {
        git fetch origin $Branch 2>$null | Out-Null
        $hash = git rev-parse "origin/$Branch" 2>$null
        return $hash.Trim()
    } catch {
        return $null
    }
}

function Test-GitUpdates {
    $branch = Get-GitCurrentBranch
    $localHash = Get-GitLocalHash
    $remoteHash = Get-GitRemoteHash -Branch $branch
    
    if ($localHash -and $remoteHash -and $localHash -ne $remoteHash) {
        return @{
            HasUpdates = $true
            LocalHash = $localHash
            RemoteHash = $remoteHash
            Branch = $branch
        }
    }
    
    return @{
        HasUpdates = $false
        LocalHash = $localHash
        RemoteHash = $remoteHash
        Branch = $branch
    }
}

function Invoke-GitPull {
    param([string]$Branch = "master")
    
    Write-Host ""
    Write-Host "  ============================================================" -ForegroundColor Magenta
    Write-Host "  GIT UPDATE DETECTED - Pulling changes..." -ForegroundColor Magenta
    Write-Host "  ============================================================" -ForegroundColor Magenta
    Write-Host ""
    
    Write-Log "Pulling latest changes from origin/$Branch..." -Level INFO
    
    try {
        # Stash any local changes
        $stashResult = git stash 2>&1
        $hasStash = $stashResult -notmatch "No local changes"
        
        # Pull changes
        $pullResult = git pull origin $Branch 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  [OK] Successfully pulled updates!" -ForegroundColor Green
            
            if ($hasStash) {
                git stash pop 2>&1 | Out-Null
            }
            
            return $true
        } else {
            Write-Host "  [ERROR] Pull failed: $pullResult" -ForegroundColor Red
            
            if ($hasStash) {
                git stash pop 2>&1 | Out-Null
            }
            
            return $false
        }
    } catch {
        Write-Host "  [ERROR] Git pull error: $_" -ForegroundColor Red
        return $false
    }
}

function Invoke-AutoUpdate {
    param(
        [bool]$RestartServer = $true,
        [ref]$RequestCount,
        [ref]$ErrorCount
    )
    
    $branch = Get-GitCurrentBranch
    $updateInfo = Test-GitUpdates
    
    if ($updateInfo.HasUpdates) {
        Write-Host ""
        Write-Host "  ============================================================" -ForegroundColor Magenta
        Write-Host "  [UPDATE] New version detected on GitHub!" -ForegroundColor Magenta
        Write-Host "  ============================================================" -ForegroundColor Magenta
        Write-Host ""
        Write-Host "  Local:  $($updateInfo.LocalHash.Substring(0,7))" -ForegroundColor Gray
        Write-Host "  Remote: $($updateInfo.RemoteHash.Substring(0,7))" -ForegroundColor Magenta
        Write-Host ""
        
        # Stop server
        if ($RestartServer -and $Script:ServerProcess -and -not $Script:ServerProcess.HasExited) {
            Write-Host "  Stopping server for update..." -ForegroundColor Yellow
            Stop-DevServer
        }
        
        # Pull changes
        $success = Invoke-GitPull -Branch $branch
        
        if ($success) {
            # Check if dependencies need update
            if (Test-Path "package.json") {
                Write-Host "  Checking for dependency updates..." -ForegroundColor Cyan
                
                $pkgMgr = if ($Script:PackageManager -eq "bun") { "bun" } else { "npm" }
                & $pkgMgr install 2>&1 | Out-Null
                
                Write-Host "  [OK] Dependencies updated" -ForegroundColor Green
            }
            
            # Regenerate Prisma client if schema changed
            if (Test-Path "prisma\schema.prisma") {
                Write-Host "  Checking Prisma schema..." -ForegroundColor Cyan
                npx prisma generate 2>&1 | Out-Null
            }
            
            if ($RestartServer) {
                Write-Host ""
                Write-Host "  Restarting server..." -ForegroundColor Yellow
                $Script:Restarting = $true
                
                Start-Sleep -Seconds 2
                
                # Restart the server
                Start-DevServerInternal
                
                Write-Host ""
                Write-Host "  ============================================================" -ForegroundColor Green
                Write-Host "  UPDATE COMPLETE - Server restarted!" -ForegroundColor Green
                Write-Host "  ============================================================" -ForegroundColor Green
                Write-Host ""
                
                if ($RequestCount) { $RequestCount.Value = 0 }
                if ($ErrorCount) { $ErrorCount.Value = 0 }
            }
        }
    }
    
    $Script:LastCommitHash = Get-GitLocalHash
    $Script:Restarting = $false
}

function Start-DevServer {
    param([switch]$WithMonitor)
    
    Write-Header "Starting Development Server"
    
    Write-Log "Starting development server..." -Level INFO
    
    # Initialize git tracking if git is available
    if (Test-CommandExists "git") {
        $Script:LastCommitHash = Get-GitLocalHash
        Write-Host ""
        Write-Host "  [UPDATE] Git tracking enabled (checking every $Script:UpdateInterval seconds)" -ForegroundColor Magenta
        Write-Host "  [UPDATE] Current commit: $($Script:LastCommitHash.Substring(0,7))" -ForegroundColor Magenta
    }
    
    Start-DevServerInternal
    
    if ($WithMonitor) {
        Start-ServerMonitor
    }
    
    return $true
}

function Start-DevServerInternal {
    # Check if port 3000 is already in use
    $portInUse = Get-NetTCPConnection -LocalPort 3000 -ErrorAction SilentlyContinue
    if ($portInUse) {
        Write-Host ""
        Write-Host "  [!] Port 3000 is already in use!" -ForegroundColor Yellow
        Write-Host "  Attempting to stop existing process..." -ForegroundColor Yellow
        
        try {
            $existingProcess = Get-Process -Id $portInUse.OwningProcess -ErrorAction SilentlyContinue
            if ($existingProcess) {
                Stop-Process -Id $existingProcess.Id -Force -ErrorAction SilentlyContinue
                Start-Sleep -Seconds 2
                Write-Host "  [OK] Stopped existing process" -ForegroundColor Green
            }
        } catch {
            Write-Host "  [WARN] Could not stop existing process" -ForegroundColor Yellow
        }
    }
    
    # Clear old server log
    if (Test-Path $Script:ServerLogPath) {
        Remove-Item $Script:ServerLogPath -Force -ErrorAction SilentlyContinue
    }
    
    # Determine start command
    $startCmd = if ($Script:PackageManager -eq "bun") {
        "bun run dev"
    } else {
        "npm run dev"
    }
    
    Write-Host ""
    Write-Host "  Starting: $startCmd" -ForegroundColor Cyan
    Write-Host "  Port: 3000" -ForegroundColor Cyan
    Write-Host "  Press Ctrl+C to stop the server" -ForegroundColor Gray
    Write-Host ""
    
    # Start the server process
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = if ($Script:PackageManager -eq "bun") { "bun" } else { "npm" }
    $psi.Arguments = "run dev"
    $psi.UseShellExecute = $false
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.WorkingDirectory = $PWD
    $psi.CreateNoWindow = $true
    
    $Script:ServerProcess = New-Object System.Diagnostics.Process
    $Script:ServerProcess.StartInfo = $psi
    
    # Register cleanup on exit
    [Console]::TreatControlCAsInput = $false
    [Console]::CancelKeyPress.Add_Handler({
        param($sender, $e)
        $e.Cancel = $true
        Stop-DevServer
        exit 0
    }.GetNewClosure())
    
    # Also register for PowerShell engine shutdown
    Register-EngineEvent -SourceIdentifier PowerShell.Exiting -Action {
        Stop-DevServer
    } -ErrorAction SilentlyContinue
    
    try {
        $null = $Script:ServerProcess.Start()
        Write-Log "Server process started (PID: $($Script:ServerProcess.Id))" -Level SUCCESS
        Write-Host "  [OK] Server started (PID: $($Script:ServerProcess.Id))" -ForegroundColor Green
    } catch {
        Write-Host "  [ERROR] Failed to start server: $_" -ForegroundColor Red
        Write-Log "Failed to start server: $_" -Level ERROR
        return $false
    }
    
    return $true
}

function Stop-DevServer {
    if ($Script:ServerProcess -and -not $Script:ServerProcess.HasExited) {
        Write-Host ""
        Write-Host "  Stopping server..." -ForegroundColor Yellow
        
        try {
            $Script:ServerProcess.Kill()
            $Script:ServerProcess.WaitForExit(5000)
            Write-Host "  [OK] Server stopped" -ForegroundColor Green
            Write-Log "Server stopped" -Level INFO
        } catch {
            Write-Host "  [WARN] Could not gracefully stop server" -ForegroundColor Yellow
        }
    }
}

function Start-ServerMonitor {
    $startTime = Get-Date
    $requestCount = 0
    $errorCount = 0
    $statusInterval = 30  # Show status every 30 seconds
    
    # Create timers
    $statusTimer = [System.Diagnostics.Stopwatch]::StartNew()
    $updateTimer = [System.Diagnostics.Stopwatch]::StartNew()
    
    Write-Host ""
    Write-Host "  ============================================================" -ForegroundColor DarkCyan
    Write-Host "  SERVER RUNNING - Real-time logs below" -ForegroundColor Cyan
    if (Test-CommandExists "git") {
        Write-Host "  Auto-update: Checking every $Script:UpdateInterval seconds" -ForegroundColor Magenta
    }
    Write-Host "  ============================================================" -ForegroundColor DarkCyan
    Write-Host ""
    
    while ($Script:ServerProcess -and -not $Script:ServerProcess.HasExited) {
        # Check for git updates every 10 seconds
        if (Test-CommandExists "git" -and -not $Script:Restarting) {
            if ($updateTimer.Elapsed.TotalSeconds -ge $Script:UpdateInterval) {
                $updateTimer.Restart()
                
                $updateInfo = Test-GitUpdates
                
                if ($updateInfo.HasUpdates) {
                    Invoke-AutoUpdate -RestartServer $true -RequestCount ([ref]$requestCount) -ErrorCount ([ref]$errorCount)
                }
            }
        }
        
        # Read standard output
        while (-not $Script:ServerProcess.StandardOutput.EndOfStream) {
            $line = $Script:ServerProcess.StandardOutput.ReadLine()
            if ($line) {
                $timestamp = Get-Date -Format "HH:mm:ss"
                
                # Color code different log types
                if ($line -match "error|Error|ERROR|failed|Failed") {
                    Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                    Write-Host $line -ForegroundColor Red
                    $errorCount++
                } elseif ($line -match "warn|Warn|WARN") {
                    Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                    Write-Host $line -ForegroundColor Yellow
                } elseif ($line -match "ready|Ready|compiled|Compiled|started|Started") {
                    Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                    Write-Host $line -ForegroundColor Green
                } elseif ($line -match "GET|POST|PUT|DELETE|PATCH") {
                    Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                    Write-Host $line -ForegroundColor Cyan
                    $requestCount++
                } elseif ($line -match "localhost:3000|http://") {
                    Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                    Write-Host $line -ForegroundColor Green
                } else {
                    Write-Host "  [$timestamp] $line" -ForegroundColor Gray
                }
                
                Add-Content -Path $Script:ServerLogPath -Value "[$timestamp] $line" -ErrorAction SilentlyContinue
            }
        }
        
        # Read error output
        while (-not $Script:ServerProcess.StandardError.EndOfStream) {
            $line = $Script:ServerProcess.StandardError.ReadLine()
            if ($line) {
                $timestamp = Get-Date -Format "HH:mm:ss"
                Write-Host "  [$timestamp] " -NoNewline -ForegroundColor Gray
                Write-Host $line -ForegroundColor Red
                $errorCount++
                Add-Content -Path $Script:ServerLogPath -Value "[$timestamp] [ERROR] $line" -ErrorAction SilentlyContinue
            }
        }
        
        # Show periodic status
        if ($statusTimer.Elapsed.TotalSeconds -ge $statusInterval) {
            $statusTimer.Restart()
            Show-ServerStatus -RequestCount $requestCount -ErrorCount $errorCount -StartTime $startTime
        }
        
        Start-Sleep -Milliseconds 100
    }
    
    # Process exited
    if ($Script:ServerProcess.HasExited -and -not $Script:Restarting) {
        Write-Host ""
        Write-Host "  ============================================================" -ForegroundColor Red
        Write-Host "  SERVER STOPPED" -ForegroundColor Red
        Write-Host "  Exit Code: $($Script:ServerProcess.ExitCode)" -ForegroundColor Yellow
        Write-Host "  ============================================================" -ForegroundColor Red
        
        $uptime = ((Get-Date) - $startTime).ToString("hh\:mm\:ss")
        Write-Host ""
        Write-Host "  Session Statistics:" -ForegroundColor Cyan
        Write-Host "  - Uptime: $uptime" -ForegroundColor Gray
        Write-Host "  - Total Requests: $requestCount" -ForegroundColor Gray
        Write-Host "  - Errors: $errorCount" -ForegroundColor $(if ($errorCount -gt 0) { "Red" } else { "Gray" })
        Write-Host "  - Log file: $Script:ServerLogPath" -ForegroundColor Gray
    }
}

function Show-ServerStatus {
    param(
        [int]$RequestCount,
        [int]$ErrorCount,
        [datetime]$StartTime
    )
    
    $uptime = ((Get-Date) - $StartTime).ToString("hh\:mm\:ss")
    
    # Check port status
    $portStatus = Get-NetTCPConnection -LocalPort 3000 -ErrorAction SilentlyContinue
    $connections = ($portStatus | Measure-Object).Count
    
    # Get memory usage
    $memoryStr = if ($Script:ServerProcess -and -not $Script:ServerProcess.HasExited) {
        try {
            $proc = Get-Process -Id $Script:ServerProcess.Id -ErrorAction SilentlyContinue
            if ($proc) {
                "{0:N0} MB" -f ($proc.WorkingSet64 / 1MB)
            } else { "N/A" }
        } catch { "N/A" }
    } else { "N/A" }
    
    # Get git info
    $gitBranch = Get-GitCurrentBranch
    $gitHash = Get-GitLocalHash
    $gitHashShort = if ($gitHash) { $gitHash.Substring(0,7) } else { "N/A" }
    
    Write-Host ""
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "SERVER STATUS" -NoNewline -ForegroundColor Cyan
    Write-Host "                                              |" -ForegroundColor DarkGray
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "URL: " -NoNewline -ForegroundColor White
    Write-Host "http://localhost:3000" -NoNewline -ForegroundColor Green
    Write-Host "                          |" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "Uptime: " -NoNewline -ForegroundColor White
    Write-Host "$uptime".PadRight(8) -NoNewline -ForegroundColor Cyan
    Write-Host "  Memory: " -NoNewline -ForegroundColor White
    Write-Host "$memoryStr".PadLeft(10) -NoNewline -ForegroundColor Yellow
    Write-Host "       |" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "Active Connections: " -NoNewline -ForegroundColor White
    Write-Host "$connections".PadLeft(2) -NoNewline -ForegroundColor Green
    Write-Host "   Total Requests: " -NoNewline -ForegroundColor White
    Write-Host "$requestCount".PadLeft(5) -NoNewline -ForegroundColor Cyan
    Write-Host "   |" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "Errors: " -NoNewline -ForegroundColor White
    $errorColor = if ($ErrorCount -gt 0) { "Red" } else { "Green" }
    Write-Host "$ErrorCount".PadLeft(3) -NoNewline -ForegroundColor $errorColor
    Write-Host "                                                  |" -ForegroundColor DarkGray
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor DarkGray
    Write-Host "  | " -NoNewline -ForegroundColor DarkGray
    Write-Host "Git: " -NoNewline -ForegroundColor White
    Write-Host "$gitBranch" -NoNewline -ForegroundColor Magenta
    Write-Host " @ " -NoNewline -ForegroundColor Gray
    Write-Host "$gitHashShort" -NoNewline -ForegroundColor Magenta
    Write-Host "                               |" -ForegroundColor DarkGray
    Write-Host "  +------------------------------------------------------------+" -ForegroundColor DarkGray
    Write-Host ""
}

function Test-ServerRunning {
    param([int]$Port = 3000, [int]$TimeoutSeconds = 30)
    
    Write-Host "  Waiting for server to be ready" -NoNewline -ForegroundColor Cyan
    
    $maxAttempts = $TimeoutSeconds * 2
    $attempts = 0
    
    while ($attempts -lt $maxAttempts) {
        $attempts++
        
        try {
            $tcpClient = New-Object System.Net.Sockets.TcpClient
            $connect = $tcpClient.BeginConnect("localhost", $Port, $null, $null)
            $wait = $connect.AsyncWaitHandle.WaitOne(500)
            
            if ($wait) {
                try {
                    $tcpClient.EndConnect($connect)
                    $tcpClient.Close()
                    Write-Host " [OK]" -ForegroundColor Green
                    Write-Host "  Server is running on port $Port" -ForegroundColor Green
                    return $true
                } catch { }
            }
            
            $tcpClient.Close()
        } catch { }
        
        Write-Host "." -NoNewline -ForegroundColor Cyan
        Start-Sleep -Milliseconds 500
    }
    
    Write-Host " [FAILED]" -ForegroundColor Red
    Write-Host "  Server did not start within $TimeoutSeconds seconds" -ForegroundColor Red
    return $false
}

function Show-SuccessMessage {
    Write-Header "Setup Complete!"
    
    Write-Host "  $($Config.AppName) v$($Config.Version)" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Next Steps:" -ForegroundColor White
    Write-Host "  1. Start the development server:" -ForegroundColor Gray
    Write-Host "     .\start.ps1" -ForegroundColor Green
    Write-Host ""
    Write-Host "  2. Or run manually:" -ForegroundColor Gray
    Write-Host "     bun run dev" -ForegroundColor Green
    Write-Host ""
    Write-Host "  3. Open in browser:" -ForegroundColor Gray
    Write-Host "     http://localhost:3000" -ForegroundColor Green
    Write-Host ""
    Write-Host "  4. Configure API keys in Settings (optional)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  Documentation: https://github.com/Shootre21/political-spectrum-app-v2" -ForegroundColor DarkGray
    Write-Host "  Log file: $LogFile" -ForegroundColor DarkGray
    Write-Host ""
}

# ============================================
# MAIN EXECUTION
# ============================================
function Main {
    $startTime = Get-Date
    
    # Initialize log
    try {
        "" | Out-File -FilePath $LogFile -Encoding utf8 -Force
    } catch {
        $LogFile = ".\setup-$(Get-Date -Format 'yyyyMMddHHmmss').log"
    }
    
    Write-Header "$($Config.AppName) Setup v$($Config.Version)"
    
    Write-Log "Starting setup process" -Level INFO
    Write-Log "PowerShell version: $($PSVersionTable.PSVersion)" -Level DEBUG
    Write-Log "Working directory: $PWD" -Level DEBUG
    
    # Calculate total steps
    $totalSteps = 7
    if (-not $SkipDeps) { $totalSteps++ }
    if (-not $SkipDB) { $totalSteps++ }
    if (-not $SkipEnv) { $totalSteps++ }
    Reset-Progress -Total $totalSteps
    
    try {
        # Step 1: Prerequisites
        Invoke-PrerequisitesCheck
        
        # Step 2: Dependencies
        if (-not $SkipDeps) {
            Invoke-DependencyInstall
        }
        
        # Step 3: Database
        if (-not $SkipDB) {
            Invoke-DatabaseSetup
        }
        
        # Step 4: Environment
        if (-not $SkipEnv) {
            Invoke-EnvironmentSetup
        }
        
        # Step 5: Credentials prompt
        Invoke-CredentialsPrompt
        
        # Step 6: Build check
        Invoke-BuildCheck
        
        # Step 7: Final checks
        Invoke-FinalChecks
        
        # Show summary
        Show-ErrorSummary
        
        # Show success message if no fatal errors
        if ($Script:Errors | Where-Object { $_.Fatal }) {
            Write-Host "`n  Setup completed with errors. Please fix the issues above." -ForegroundColor Yellow
        } else {
            Show-SuccessMessage
        }
        
    } catch {
        Write-Host "`n  Setup failed: $_" -ForegroundColor Red
        Write-Log "Setup failed: $_" -Level ERROR
        Show-ErrorSummary
        exit 1
    }
    
    $duration = ((Get-Date) - $startTime).TotalSeconds
    Write-Log "Setup completed in $([Math]::Round($duration, 1)) seconds" -Level INFO
    
    # Write summary to log
    $summary = @"

========================================
SETUP SUMMARY
========================================
Timestamp: $(Get-Date)
Duration: $([Math]::Round($duration, 1)) seconds
Errors: $($Script:Errors.Count)
Warnings: $($Script:Warnings.Count)
Log File: $LogFile
========================================
"@
    
    Add-Content -Path $LogFile -Value $summary
    
    # Start server if requested or prompt user
    if (-not ($Script:Errors | Where-Object { $_.Fatal })) {
        if ($Start) {
            # Auto-start requested
            Start-DevServer -WithMonitor
        } elseif (-not $NoMonitor) {
            # Ask user if they want to start
            Write-Host ""
            Write-Host "  ============================================================" -ForegroundColor Cyan
            Write-Host "  Would you like to start the development server now?" -ForegroundColor White
            Write-Host "  [Y] Yes, start server  [N] No, exit" -ForegroundColor Gray
            Write-Host "  ============================================================" -ForegroundColor Cyan
            Write-Host ""
            
            # Use Read-Host for reliable input
            $response = Read-Host "  Enter Y or N"
            
            if ($response -eq 'Y' -or $response -eq 'y') {
                Write-Host ""
                Start-DevServer -WithMonitor
            } else {
                Write-Host ""
                Write-Host "  To start the server later, run:" -ForegroundColor Gray
                Write-Host "  .\start.ps1" -ForegroundColor Green
                Write-Host "  or: bun run dev" -ForegroundColor Green
                Write-Host ""
                Write-Host "  Then open: http://localhost:3000" -ForegroundColor Cyan
                Write-Host ""
            }
        }
    }
}

# Run main function
Main
